# Generated by Django 4.0.5 on 2022-07-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('kakao_pk', models.BigIntegerField(unique=True)),
                ('credit', models.DecimalField(decimal_places=2, default=200000.0, max_digits=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
